/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BaseDialog: typeof import('./components/BaseDialog.vue')['default']
    FieldBox: typeof import('./components/FieldBox.vue')['default']
    FormGenerator: typeof import('./components/FormGenerator.vue')['default']
    JalaliDate: typeof import('./components/JalaliDate.vue')['default']
    ListChart: typeof import('./components/ListChart.vue')['default']
    MainsForm: typeof import('./components/MainsForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stepper: typeof import('./components/Stepper.vue')['default']
  }
}
