/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/auth/Login': RouteRecordInfo<'/auth/Login', '/auth/Login', Record<never, never>, Record<never, never>>,
    '/auth/Register': RouteRecordInfo<'/auth/Register', '/auth/Register', Record<never, never>, Record<never, never>>,
    '/Chart': RouteRecordInfo<'/Chart', '/Chart', Record<never, never>, Record<never, never>>,
    '/Creat-Strategy': RouteRecordInfo<'/Creat-Strategy', '/Creat-Strategy', Record<never, never>, Record<never, never>>,
    '/ListSignal': RouteRecordInfo<'/ListSignal', '/ListSignal', Record<never, never>, Record<never, never>>,
    '/ListSymbol': RouteRecordInfo<'/ListSymbol', '/ListSymbol', Record<never, never>, Record<never, never>>,
    '/Market': RouteRecordInfo<'/Market', '/Market', Record<never, never>, Record<never, never>>,
    '/Responseback': RouteRecordInfo<'/Responseback', '/Responseback', Record<never, never>, Record<never, never>>,
    '/ShowMarket': RouteRecordInfo<'/ShowMarket', '/ShowMarket', Record<never, never>, Record<never, never>>,
    '/Strategies': RouteRecordInfo<'/Strategies', '/Strategies', Record<never, never>, Record<never, never>>,
  }
}
